from fastapi import APIRouter
from fastapi.responses import Response
from pydantic import BaseModel
import io

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

router = APIRouter()

class DPRRequest(BaseModel):
    opportunity_id: str
    capital: float
    project_cost: float
    loan_amount: float

@router.post("/generate")
def generate_dpr(req: DPRRequest):
    if not REPORTLAB_AVAILABLE:
        # Fallback if somehow not installed, though it should be.
        return {"error": "ReportLab is not installed. PDF generation unavailable."}

    # Generate a real PDF in memory
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    # Simple layout
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 750, "Detailed Project Report (DPR)")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, 700, f"Opportunity ID: {req.opportunity_id}")
    c.drawString(50, 680, f"Margin Capital: Rs. {req.capital:,.2f}")
    c.drawString(50, 660, f"Project Cost: Rs. {req.project_cost:,.2f}")
    c.drawString(50, 640, f"Loan Amount: Rs. {req.loan_amount:,.2f}")
    
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 600, "Generated by LAND2BIZ M14 Engine (Deterministic)")
    
    c.showPage()
    c.save()
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return Response(content=pdf_bytes, media_type="application/pdf")
